### ISSUE TITLE
Replace WTFPL License by any other open license (Apache 2.0, ISC, MIT)

### ISSUE THREAD

**Issue by better-call-alex-soul** [parshap/utf8-byte-length#3]
It would be really great to replace WTFPL license from published npm artifacts

**Comment by benlangfeld** [comment]
@parshap Is this something you'd be willing to do? Can we do MIT or BSD or some other license that is already broadly acceptable to employers?

**Comment by parshap** [comment]
Sure. Same answer here: https://github.com/parshap/truncate-utf8-bytes/issues/2#issuecomment-1568825063

**Comment by nima-ap** [comment]
Hi there. Is it possible in some way to have this license applied retroactively on the latest release of the product (1.0.4) which was created 8 years ago (and hence much prior to the introduction of MIT)? Or alternatively consider releasing a new 1.0.5 _just_ with identical source as 1.0.4 so a new version is released with MIT?

Also attempting to discuss this in https://github.com/clearlydefined/curated-data/pull/26692

**Comment by parshap** [comment]
I've published 1.0.5 containing the dual license.
